server:
  port: 8080
  tomcat:
    threads:
      max: 200
    connection-timeout: 500000
  servlet:
    session:
      timeout: 500000
  jetty:
    connection-idle-timeout: 500000
  netty:
    connection-timeout: 500000
spring:
  datasource:
    url: jdbc:mysql://3.0.147.195:3306/search_room?allowPublicKeyRetrieval=true&useSSL=false
    username: house
    password: house@1234

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 288474988857-6d7pmaj52tcjosi41j439h29sv2q50sa.apps.googleusercontent.com
            client-secret: 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
          facebook:
            client-id: 1350896665750260
            client-secret: 1ab3d808315d96dc7fc667e1b0f3350a
  mail:
    host: smtp.gmail.com
    port: 587
    username: managermenthouse@gmail.com
    password: bfttwdikraonuwuw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # ===============================
  # = JPA configurations
  # ===============================s
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: MYSQL
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

security:
  jwt:
    token:
      secret-key: secret-key

app:
  admin:
    username: admin
    password: admin

solr:
  url: http://35.247.146.225:8500/solr

logging:
  config: config/log4j2.yml